# Generated by Django 5.0.6 on 2024-05-26 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_color_item_gender_item_size_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='fuel_type',
            field=models.CharField(blank=True, default='Unknown Fuel Type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='Thimphu', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='make',
            field=models.CharField(default='Maruti Suzuki', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='transmission',
            field=models.CharField(blank=True, default='Unknown Transmission', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.PositiveIntegerField(default=2010),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='item.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
