# Generated by Django 5.0.6 on 2024-05-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_gender_remove_item_name_remove_item_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='make',
            new_name='name',
        ),
    ]
